---
abstract: 'represents a WMA/ASF audio file'
author:
  - 'Nathaniel Heinrichs <nheinric@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-File-Wma
no_index:
  directory:
    - inc
    - t
requires:
  Audio::File: 0
  Audio::WMA: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01a
